version: "3.8"

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "db_local:/var/lib/postgresql/data"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=lunch
    networks:
      - compose-network
#
#  lunch:
#    image: lunch:local-latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    networks:
#      - compose-network


networks:
  compose-network:

volumes:
  db_local:
    driver: local

