
..server:
  port: 8080

---
spring:
  application:
    name: Lunch

---
logging:
  level:
    com.example: debug

---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lunch
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.investidea.tech/auth/realms/pokemon
          jwk-set-uri: https://keycloak.investidea.tech/auth/realms/pokemon/protocol/openid-connect/certs
